In [64]:
#importing necessary librarires
import random
import numpy as np
from sklearn.utils import shuffle



In [68]:
#creating empty rows to store the values
age = []
sideeff= []

In [11]:
#adding values persons with 65 or below 
for i in range(1050):
    val=np.random.randint(13,65)
    age.append(val)
    

In [12]:
#adding values into the age array ,persons with age 65 or above
for i in range(1050):
    val =np.random.randint(65,100)
    age.append(val)

In [18]:

#To add values in side effects array 
#chnge 0 and 1 once
for i in range(1000):
    sideeff.append(0)  
for i in range(50):
    sideeff.append(1)
    
    


In [24]:
import pandas as pd

In [39]:
#convering it into dataframe
df = pd.DataFrame(
    {'age':age,
    'sideeffects':sideeff}
)

In [65]:
#converting it into array but why??? because the fit function expects array as input or few other types as input
train_labels =  np.array(df['sideeffects'])
train_labels
train_samples = np.array(df['age'])
train_samples
train_labels,train_samples=shuffle(train_labels,train_samples)

In [70]:
train_labels,train_samples

(array([0, 0, 1, ..., 1, 1, 1], dtype=int64),
 array([99, 66, 36, ..., 43, 51, 63], dtype=int64))

In [71]:
from sklearn.preprocessing import MinMaxScaler

In [76]:
scaler = MinMaxScaler(feature_range=(0,1))
scaled_train_samples = scaler.fit_transform(train_samples.reshape(-1,1)) #fit transform doesnt accept 1 dim data so reshape

array([[99],
       [66],
       [36],
       ...,
       [43],
       [51],
       [63]], dtype=int64)

In [88]:
##simple tf.keras sequential model
#importing necessary libraries 

In [105]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Activation,Dense
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.metrics import categorical_crossentropy


In [102]:
model = Sequential(
    [
        Dense(units=16,input_shape=(1,),activation='relu'),
        Dense(units=32,activation='relu'),
        Dense(units=2,activation='softmax')
    ]
)

In [103]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                      │ (None, 16)                  │              32 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_4 (Dense)                      │ (None, 32)                  │             544 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_5 (Dense)                      │ (None, 2)                   │              66 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 642 (2.51 KB)

 Trainable params: 642 (2.51 KB)

 Non-trainable params: 0 (0.00 B)

In [107]:
model.compile(optimizer=Adam(learning_rate=0.0001),loss='sparse_categorical_crossentropy',metrics=['accuracy'])

In [111]:
model.fit(x=scaled_train_samples,y=train_labels,batch_size=10,epochs=30)

Epoch 1/30
210/210 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.5036 - loss: 0.7161 
Epoch 2/30
210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7183 - loss: 0.6827 
Epoch 3/30
210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7551 - loss: 0.6498  
Epoch 4/30
210/210 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7771 - loss: 0.6224 
Epoch 5/30
210/210 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7802 - loss: 0.5956  
Epoch 6/30
210/210 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8034 - loss: 0.5639  
Epoch 7/30
210/210 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8225 - loss: 0.5349 
Epoch 8/30
210/210 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8299 - loss: 0.5046 
Epoch 9/30
210/210 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8424 - loss: 0.4838 
Epoch 10/30
210/210 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8613 - loss: 0.4557  
Epoch 11/30
210/210 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8851 - loss: 0.4254  
Epoch 12/30
210/210 ━━━━━━━━━━━━━━━━